### ISSUE TITLE
Batch request with System.InvalidOperationException: This operation is not supported for a relative URI

### ISSUE THREAD

**Issue by tmytn** [iwate/ODataHttpClient#17]
Hi Team, 
I have a question about creating a $batch of items using OdataClient However we get the exception : System.InvalidOperationException: This operation is not supported for a relative URI. 
 var responses = await _oDataClient.SendAsync(batch).ConfigureAwait(false);

I have a function to init the batch variable:
public BatchRequest InitBatchRequest (List<MyItem> myItems){
            var batch = new BatchRequest(_uriBatch);
            foreach (var item in myItems)
            {
                var req = Request.Post(_uriSingle, item);
                batch.Requests.Add(req);
            }
            return batch;
        }
I appreciate your any insight to resolve the issue. 
Thank you
Nhat

**Comment by iwate** [comment]
Hi @tmytn 

ODataHttpClient needs absolute URI all request. like as

```
var endpoint = "https://example.com/odata.svc";
var batch = new BatchRequest($"{endpoint}/$batch")
{
    Requests = new []
    {
        Request.Post($"{endpoint}/Products", new 
        { 
            Name = "Sample"
        }),
        Request.Post($"{endpoint}/$1/$links/Categories", new 
        {
            url = $"{endpoint}/Categories(0)"
        })
    }
};
```
We cannot change this spec because `System.Uri` ( inner of `Syste.Net.Http.HttpRequestMessage`) needs absolute URI.
https://github.com/iwate/ODataHttpClient/blob/65506e88285c350a761865689857e1a50c538492/src/ODataHttpClient/Models/Request.cs#L26
