### ISSUE TITLE
Support for List<T>?

### ISSUE THREAD

**Issue by paulbrinson** [iwate/ODataHttpClient#21]
I tried creating a PATCH request for a list of objects like this:

var listOfObjects = new List<SomeObject>() { new SomeObject() { Property1 = "test1" }, new SomeObject() { Property1 = "test2" } };
Request.Patch<List<SomeObject>>("some_uri", listOfObjects);

and got the following error:

One or more errors occurred. (Object serialized to Array. JObject instance expected.)

Does the Create<T> method of the Request class need to support JArray.FromObject(...)?

**Comment by iwate** [comment]
Hi, @paulbrinson

Would you tell me what context url do you want to request?
http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_ContextURL

I think the case patch which need to replace list of objects  is `{context-url}#{entity}/{property-path}{select-list}` .
However you can use patch `{context-url}#{entity}` for it.

If you replace `{context-url}#{entity-set}`, you can use batch request:)
