### ISSUE TITLE
Boolean values have wrong format on german system

### ISSUE THREAD

**Issue by bxbxbx** [iwate/ODataHttpClient#23]
Hi @iwate,

first thanks for your very clean and simple code, it was a pleasant read.

I found an issue, that will probably only occur on non english systems like my german one.
Boolean values will be formated as True or False (please notice the uppercase leading character), 
which seems not to be the standard format for OData, which mandates all lowercase.

A simple fix which works is to treat booleans as a separate type in the parameterizers

    case bool val: return Literal(val);

    private string Literal(bool value) => value ? "true" : "false";

**Comment by iwate** [comment]
@bxbxbx Thank you for your contribution.
I make a few commits for your issue.

6c92cf674b72e4bcd2de90c2667ec31149f3fe92 add tests
cac9dae5033dd8b106cadf0d160cc795e571479d add your patch

**Comment by bxbxbx** [comment]
@iwate 

Excellent thanks for the quick reply. 

Now if you would please consider merging the pull request from @psmolich79, that would be fantastic, because then the lib would be  truly globally usable.

**Comment by iwate** [comment]
I've released new version 1.7.1 which contains the PR #24 .
