### ISSUE TITLE
Is it support odata open type ?

### ISSUE THREAD

**Issue by dks07** [iwate/ODataHttpClient#26]
Is it support odata open type out of the box as Newtonsoft json serialize and deserialize does not support it ?

Is there any special serialization setting which we need to provide ?

**Comment by iwate** [comment]
@dks07 
 You can implement original json serializer and replace default serializer instance.
 
 ```
public class MySerializer :  ODataHttpClient.Serializers.IJsonSerializer {}
public static void Main() {
    ODataHttpClient.Serializers.JsonSerializer.Default = new MySerializer();
}
 ```
  
However, I think `Response.ReadAs<Type>("<json path>")` is enough at various use cases.

If you can write your json response payload, I may help you more.
