### ISSUE TITLE
Why enforce async/await method?

### ISSUE THREAD

**Issue by neonleo** [iwate/ODataHttpClient#46]
I would like use it in console and not async/await, how can I post/get in generic way?
Thanks

**Comment by iwate** [comment]
@neonleo 
You can use async main method after c# 7.1.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.1/async-main

If you use c# ~v7.0, you can wrap mainasync method.
```
public static void Main()
{
    MainAsync().GetAwaiter().GetResult();
}

private static async Task MainAsync()
{
    ...
    var response = await odata.SendAsync(...);
}
```

And you can also use `Task.Result`.

```
public static void Main()
{
    ...
    var response = await odata.SendAsync(...).Result;
}
```
