### ISSUE TITLE
ODataParameterizer unintentionally replaces `$$` with `$`

### ISSUE THREAD

**Issue by xin9le** [iwate/ODataHttpClient#53]
# Summary
`ODataParameterizer` and `ODataV4Parameterizer` replaces `$$` in string with `$`. This is because `Regex.Replace` replaces the `$` character. We expect that any string containing `$$` will be expanded directly into the query.

- https://github.com/iwate/ODataHttpClient/blob/a076beefec76e960b5d8a2c3af17bc6b9357d13e/src/ODataHttpClient/Parameterizers/ODataV4Parameterizer.cs#L25
- https://learn.microsoft.com/ja-jp/dotnet/standard/base-types/substitutions-in-regular-expressions#substituting-a--character

# Reproduction Code

```
// new { x = "$$abc$$" }
$filter=value eq @x
```
```
// $ is vanished
$filter=value eq '$abc$'
```

**Comment by iwate** [comment]
@xin9le Thank you for your report. I've fix it at 680e9d50461dbb73a2fa40b4f5429a27dc222943.
I release new version soon.
