### ISSUE TITLE
Add custom header field to each request

### ISSUE THREAD

**Issue by iwate** [iwate/ODataHttpClient#8]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%242%20Funded-%2300A156.svg" />](https://issuehunt.io/r/iwate/ODataHttpClient/issues/8)

When use following features, need to set field in request headers.

If-Match
If-None-Match

## Plan

* add Headers property to Request class
* add headers parameters Request factory method
* set Headers to HttpRequestMessage instance in Request#CreateMethod
* add Headers Property to Response class
* copy headers to Response from HttpResponseMessage

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $2.00)

- [<img src='https://avatars1.githubusercontent.com/u/1011232?v=4' alt='iwate' width=24 height=24> iwate](https://issuehunt.io/u/iwate) ($2.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/iwate/ODataHttpClient/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by marcnet80** [comment]
Hello, @iwate. Is this task still actual? 
If yes, could you please provide more details?

**Comment by iwate** [comment]
HI, @marcnet80 !

> Is this task still actual?

Yes!, I update a implemention plan. please check it!

Would you tell me your idea if you have opinion :)

**Comment by marcnet80** [comment]
@iwate thank you for description, I will create pull-request today, result will be like this:
<pre>
var client = new HttpClient();
var odata = new ODataClient(client);
var headers = new HttpRequestMessage().Headers;
headers.TryAddWithoutValidation("If-Match", "*");
var request = Request.Create(HttpMethod.Get ,$"{Endpoint}", headers);
var response = await odata.SendAsync(request);
Assert.True(response.Headers.Contains(headers.First().Key)); // true
</pre>

**Comment by iwate** [comment]
@marcnet80 Thank you for your contribute!
